-- Create table for detailed DMT transaction records
CREATE TABLE `dmt_transaction_details` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `recharge_id` bigint(20) DEFAULT NULL COMMENT 'Reference to recharges table',
  `user_id` bigint(20) NOT NULL COMMENT 'User who initiated the transaction',
  `remitter_mobile` varchar(15) NOT NULL COMMENT 'Remitter mobile number',
  `remitter_name` varchar(255) DEFAULT NULL COMMENT 'Remitter full name',
  `beneficiary_id` varchar(50) NOT NULL COMMENT 'Beneficiary ID from InstantPay',
  `beneficiary_name` varchar(255) NOT NULL COMMENT 'Beneficiary name',
  `beneficiary_account` varchar(50) NOT NULL COMMENT 'Beneficiary account number',
  `beneficiary_ifsc` varchar(15) NOT NULL COMMENT 'Beneficiary IFSC code',
  `beneficiary_bank_name` varchar(255) DEFAULT NULL COMMENT 'Bank name',
  `beneficiary_mobile` varchar(15) DEFAULT NULL COMMENT 'Beneficiary mobile number',
  `transaction_amount` decimal(10,2) NOT NULL COMMENT 'Transaction amount',
  `transfer_mode` varchar(10) NOT NULL DEFAULT 'IMPS' COMMENT 'Transfer mode - IMPS/NEFT/RTGS',
  `transaction_charges` decimal(10,2) DEFAULT 0.00 COMMENT 'Transaction charges',
  `gst_amount` decimal(10,2) DEFAULT 0.00 COMMENT 'GST amount',
  `total_deducted` decimal(10,2) NOT NULL COMMENT 'Total amount deducted from user',
  `external_ref` varchar(100) DEFAULT NULL COMMENT 'External reference ID',
  `pool_reference_id` varchar(100) DEFAULT NULL COMMENT 'Pool reference ID from InstantPay',
  `txn_reference_id` varchar(100) DEFAULT NULL COMMENT 'Transaction reference ID',
  `ipay_uuid` varchar(255) DEFAULT NULL COMMENT 'InstantPay UUID',
  `order_id` varchar(100) DEFAULT NULL COMMENT 'Order ID from InstantPay',
  `pool_account` varchar(20) DEFAULT NULL COMMENT 'Pool account used',
  `pool_opening_balance` decimal(15,2) DEFAULT NULL COMMENT 'Pool opening balance',
  `pool_closing_balance` decimal(15,2) DEFAULT NULL COMMENT 'Pool closing balance',
  `status` enum('SUCCESS','FAILED','PENDING','REFUNDED') NOT NULL DEFAULT 'PENDING' COMMENT 'Transaction status',
  `api_status_code` varchar(10) DEFAULT NULL COMMENT 'API status code from InstantPay',
  `api_status_message` text DEFAULT NULL COMMENT 'API status message',
  `failure_reason` text DEFAULT NULL COMMENT 'Failure reason if transaction failed',
  `user_balance_before` decimal(15,2) DEFAULT NULL COMMENT 'User balance before transaction',
  `user_balance_after` decimal(15,2) DEFAULT NULL COMMENT 'User balance after transaction',
  `commission_earned` decimal(10,2) DEFAULT 0.00 COMMENT 'Commission earned by user',
  `latitude` decimal(10,8) DEFAULT NULL COMMENT 'Transaction latitude',
  `longitude` decimal(11,8) DEFAULT NULL COMMENT 'Transaction longitude',
  `transaction_timestamp` timestamp NULL DEFAULT NULL COMMENT 'Transaction timestamp from API',
  `environment` varchar(10) DEFAULT 'LIVE' COMMENT 'Environment - LIVE/TEST',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_remitter_mobile` (`remitter_mobile`),
  KEY `idx_beneficiary_id` (`beneficiary_id`),
  KEY `idx_beneficiary_account` (`beneficiary_account`),
  KEY `idx_external_ref` (`external_ref`),
  KEY `idx_pool_reference_id` (`pool_reference_id`),
  KEY `idx_txn_reference_id` (`txn_reference_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_ipay_uuid` (`ipay_uuid`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_recharge_id` (`recharge_id`),
  CONSTRAINT `fk_dmt_transaction_details_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_dmt_transaction_details_recharge` FOREIGN KEY (`recharge_id`) REFERENCES `recharges` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Detailed DMT transaction records for user view';

-- Add indexes for better performance
CREATE INDEX `idx_transaction_date_user` ON `dmt_transaction_details` (`user_id`, `created_at`);
CREATE INDEX `idx_beneficiary_user` ON `dmt_transaction_details` (`user_id`, `beneficiary_account`);
CREATE INDEX `idx_remitter_user` ON `dmt_transaction_details` (`user_id`, `remitter_mobile`);
